# Simple requests + limits review.
apiVersion: v1
kind: Pod
metadata:
  name: limits-demo
spec:
  containers:
  - name: nginx
    image: nginx

    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"

      limits:
        cpu: "500m"
        memory: "256Mi"