apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-db-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore

  target:
    name: database-secret

  data:
  - secretKey: password
    remoteRef:
      key: production/database
      property: password