apiVersion: v1
kind: Pod
metadata:
  name: logging-pod
spec:
  containers:
  - name: logger
    image: busybox
    command:
    - sh
    - -c
    - |
      while true
      do
        echo "$(date) application running"
        sleep 5
      done