apiVersion: v1
kind: Pod
metadata:
  name: metrics-pod
spec:
  containers:
  - name: stress
    image: busybox
    command:
    - sh
    - -c
    - |
      while true
      do
        dd if=/dev/zero of=/dev/null
      done
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 128Mi