apiVersion: v1
kind: Pod
metadata:
  name: nginx-affinity-preferred

spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: workload
            operator: In
            values:
            - database

  containers:
  - name: nginx
    image: nginx