# Application expects data somewhere else.
apiVersion: v1
kind: Pod
metadata:
  name: broken-mountpath-demo
spec:
  containers:
  - name: app
    image: nginx

    volumeMounts:
    - name: data
      mountPath: /wrong-path

  volumes:
  - name: data
    emptyDir: {}