apiVersion: v1
kind: PersistentVolume
metadata:
  name: unbound-pv
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/unbound-pv"
