apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
spec:
  containers:
  - name: app
    image: nginx

    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: web-storage

  volumes:
  - name: web-storage
    persistentVolumeClaim:
      claimName: demo-pvc
