apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
  namespace: w2d1
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: "/data"
      name: storage-volume

  volumes:
  - name: storage-volume
    persistentVolumeClaim:
      claimName: local-pvc
