apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-job

spec:
  schedule: "*/2 * * * *"

  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60

      template:
        spec:
          restartPolicy: Never

          containers:
          - name: cleanup
            image: busybox

            command:
            - sh
            - -c
            - |
              echo "Cleanup task"
              date