apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-job

spec:
  schedule: "*/2 * * * *"

  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never

          containers:
          - name: backup
            image: busybox

            command:
            - sh
            - -c
            - |
              echo "Performing backup"
              date