apiVersion: batch/v1
kind: Job
metadata:
  name: failed-job

spec:
  backoffLimit: 3

  template:
    spec:
      restartPolicy: Never

      containers:
      - name: worker
        image: busybox
        command:
        - sh
        - -c
        - |
          echo "Simulating failure"
          exit 1