apiVersion: apps/v1
kind: DaemonSet

metadata:
  name: log-agent

spec:
  selector:
    matchLabels:
      app: log-agent

  template:
    metadata:
      labels:
        app: log-agent

    spec:
      containers:
        - name: log-agent
          image: busybox

          command:
            - sh
            - -c
            - "while true; do echo collecting logs; sleep 30; done"