apiVersion: v1
kind: Pod
metadata:
  name: cpu-pressure

spec:
  containers:
  - name: stress
    image: busybox
    command:
    - sh
    - -c
    - "while true; do :; done"

    resources:
      requests:
        cpu: "100m"
      limits:
        cpu: "200m"