apiVersion: v1
kind: Pod
metadata:
  name: memory-pressure

spec:
  containers:
  - name: memory
    image: polinux/stress

    args:
    - "--vm"
    - "1"
    - "--vm-bytes"
    - "512M"
    - "--vm-hang"
    - "1"

    resources:
      limits:
        memory: "128Mi"
      requests:
        memory: "64Mi"