apiVersion: v1
kind: Pod
metadata:
  name: broken-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:  
        - matchExpressions:
          - key: workload
            operator: In
            values:
            - database
  containers:
  - name: nginx
    image: nginx
