apiVersion: v1
kind: Pod
metadata:
  name: hostpath-demo
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: host-storage
      mountPath: /data

  volumes:
  - name: host-storage
    hostPath:
      path: /tmp/k8s-hostpath
      type: DirectoryOrCreate