apiVersion: v1
kind: Service

metadata:
  name: demo-service
  namespace: integration-lab

spec:
  selector:
    app: demo

  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

  type: ClusterIP
