apiVersion: v1
kind: Pod
metadata:
  name: secure
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault

  containers:
    - name: nginx
      image: nginx:latest

      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true

        capabilities:
          drop:
            - ALL

      ports:
        - containerPort: 80

      volumeMounts:
        - name: cache
          mountPath: /var/cache/nginx

        - name: run
          mountPath: /var/run

  volumes:
    - name: cache
      emptyDir: {}

    - name: run
      emptyDir: {}