apiVersion: batch/v1
kind: CronJob
metadata:
  name: suspended-cronjob
spec:
  schedule: "*/1 * * * *"

  suspend: true

  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never

          containers:
            - name: demo
              image: busybox
              command:
                - /bin/sh
                - -c
                - date
                